POST http://localhost:9000
Content-Type: application/json;charset=utf-8
Accept: application/json
Tallyrequest : Import
Type: Data
Id : Vouchers

{
    "static_variables": [
        {
            "name": "svVchImportFormat",
            "value": "jsonex"
        },
        {
            "name": "svCurrentCompany",
            "value": "Sacet"
        }
    ],
     "tallymessage": [
        {
            "metadata": {
                "type": "Voucher", 
                "vchtype": "Sales", 
                "action": "Create", 
                "objview": "Invoice Voucher View"
            }, 
            "oldauditentryids": [
                {
                    "metadata": true, 
                    "type": "Number"
                }, 
                "-1"
            ], 
            "date": "20250401", 
            "vchstatusdate": "20250401", 
            "gstregistrationtype": "Regular", 
            "vatdealertype": "Regular", 
            "statename": "Andhra Pradesh", 
            "countryofresidence": "India", 
            "placeofsupply": "Andhra Pradesh", 
            "vouchertypename": "Sales", 
            "partyname": "Kumar2", 
            "gstregistration": {
                "value": "Andhra Pradesh Registration", 
                "taxtype": "GST", 
                "taxregistration": ""
            }, 
            "partyledgername": "Kumar2", 
            "vouchernumber": "1", 
            "basicbuyername": "Kumar2", 
            "cmpgstregistrationtype": "Regular", 
            "partymailingname": "Kumar2", 
            "consigneemailingname": "Kumar2", 
            "consigneestatename": "Andhra Pradesh", 
            "cmpgststate": "Andhra Pradesh", 
            "consigneecountryname": "India", 
            "basicbasepartyname": "Kumar2", 
            "numberingstyle": "Auto Retain", 
            "cstformissuetype": "\u0004 Not Applicable", 
            "cstformrecvtype": "\u0004 Not Applicable", 
            "fbtpaymenttype": "Default", 
            "persistedview": "Invoice Voucher View", 
            "vchstatustaxadjustment": "Default", 
            "vchstatusvouchertype": "Sales", 
            "vchstatustaxunit": "Andhra Pradesh Registration", 
            "vchgstclass": "\u0004 Not Applicable", 
            "vchentrymode": "Item Invoice", 
            "diffactualqty": false, 
            "ismstfromsync": false, 
            "isdeleted": false, 
            "issecurityonwhenentered": false, 
            "asoriginal": false, 
            "audited": false, 
            "iscommonparty": false, 
            "forjobcosting": false, 
            "isoptional": false, 
            "effectivedate": "20250401", 
            "useforexcise": false, 
            "isforjobworkin": false, 
            "allowconsumption": false, 
            "useforinterest": false, 
            "useforgainloss": false, 
            "useforgodowntransfer": false, 
            "useforcompound": false, 
            "useforservicetax": false, 
            "isreversechargeapplicable": false, 
            "issystem": false, 
            "isfetchedonly": false, 
            "isgstoverridden": false, 
            "iscancelled": false, 
            "isonhold": false, 
            "issummary": false, 
            "isecommercesupply": false, 
            "isboenotapplicable": false, 
            "isgstsecsevenapplicable": false, 
            "ignoreeinvvalidation": false, 
            "cmpgstisothterritoryassessee": false, 
            "partygstisothterritoryassessee": false, 
            "irnjsonexported": false, 
            "irncancelled": false, 
            "ignoregstconflictinmig": false, 
            "isopbaltransaction": false, 
            "ignoregstformatvalidation": false, 
            "iseligibleforitc": true, 
            "ignoregstoptionaluncertain": false, 
            "updatesummaryvalues": false, 
            "isewaybillapplicable": false, 
            "isdeletedretained": false, 
            "isnull": false, 
            "isexcisevoucher": false, 
            "excisetaxoverride": false, 
            "usefortaxunittransfer": false, 
            "isexer1nopoverwrite": false, 
            "isexf2nopoverwrite": false, 
            "isexer3nopoverwrite": false, 
            "ignoreposvalidation": false, 
            "exciseopening": false, 
            "useforfinalproduction": false, 
            "istdsoverridden": false, 
            "istcsoverridden": false, 
            "istdstcscashvch": false, 
            "includeadvpymtvch": false, 
            "issubworkscontract": false, 
            "isvatoverridden": false, 
            "ignoreorigvchdate": false, 
            "isvatpaidatcustoms": false, 
            "isdeclaredtocustoms": false, 
            "vatadvancepayment": false, 
            "vatadvpay": false, 
            "iscstdelcaredgoodssales": false, 
            "isvatrestaxinv": false, 
            "isservicetaxoverridden": false, 
            "isisdvoucher": false, 
            "isexciseoverridden": false, 
            "isexcisesupplyvch": false, 
            "gstnotexported": false, 
            "ignoregstinvalidation": false, 
            "isgstrefund": false, 
            "ovrdnewaybillapplicability": false, 
            "isvatprincipalaccount": false, 
            "vchstatusisvchnumused": false, 
            "vchgststatusisincluded": false, 
            "vchgststatusisuncertain": false, 
            "vchgststatusisexcluded": false, 
            "vchgststatusisapplicable": false, 
            "vchgststatusisgstr2breconciled": false, 
            "vchgststatusisgstr2bonlyinportal": false, 
            "vchgststatusisgstr2bonlyinbooks": false, 
            "vchgststatusisgstr2bmismatch": false, 
            "vchgststatusisgstr2bindiffperiod": false, 
            "vchgststatusisreteffdateoverrdn": false, 
            "vchgststatusisoverrdn": false, 
            "vchgststatusisstatindiffdate": false, 
            "vchgststatusisretindiffdate": false, 
            "vchgststatusmainsectionexcluded": false, 
            "vchgststatusisbranchtransferout": false, 
            "vchgststatusissystemsummary": false, 
            "vchstatusisunregisteredrcm": false, 
            "vchstatusisoptional": false, 
            "vchstatusiscancelled": false, 
            "vchstatusisdeleted": false, 
            "vchstatusisopeningbalance": false, 
            "vchstatusisfetchedonly": false, 
            "vchgststatusisoptionaluncertain": false, 
            "vchstatusisreacceptforhsndone": false, 
            "vchstatusisreaccephsnsixonedone": false, 
            "paymentlinkhasmultiref": false, 
            "isshippingwithinstate": false, 
            "isoverseastouristtrans": false, 
            "isdesignatedzoneparty": false, 
            "hascashflow": false, 
            "ispostdated": false, 
            "usetrackingnumber": false, 
            "isinvoice": true, 
            "mfgjournal": false, 
            "hasdiscounts": false, 
            "aspayslip": false, 
            "iscostcentre": false, 
            "isstxnonrealizedvch": false, 
            "isexcisemanufactureron": false, 
            "isblankcheque": false, 
            "isvoid": false, 
            "orderlinestatus": false, 
            "vatisagnstcancsales": false, 
            "vatispurcexempted": false, 
            "isvatrestaxinvoice": false, 
            "vatisassesablecalcvch": false, 
            "isvatdutypaid": true, 
            "isdeliverysameasconsignee": false, 
            "isdispatchsameasconsignor": false, 
            "isdeletedvchretained": false, 
            "vchonlyaddlinfoupdated": false, 
            "changevchmode": false, 
            "resetirnqrcode": false, 
            "alterid": " 1", 
            "masterid": " 1", 
            "voucherkey": "196481868890120", 
            "voucherretainkey": "1", 
            "vouchernumberseries": "Default", 
            "allinventoryentries": [
                {
                    "stockitemname": "Pen", 
                    "isdeemedpositive": false, 
                    "isgstassessablevalueoverridden": false, 
                    "strdisgstapplicable": false, 
                    "contentnegispos": false, 
                    "islastdeemedpositive": false, 
                    "isautonegate": false, 
                    "iscustomsclearance": false, 
                    "istrackcomponent": false, 
                    "istrackproduction": false, 
                    "isprimaryitem": false, 
                    "isscrap": false, 
                    "rate": "20.00/nos", 
                    "amount": "600.00", 
                    "actualqty": " 60.00 nos", 
                    "billedqty": " 60.00 nos", 
                    "batchallocations": [
                        {
                            "godownname": "Main Location", 
                            "batchname": "Primary Batch", 
                            "indentno": "\u0004 Not Applicable", 
                            "orderno": "\u0004 Not Applicable", 
                            "trackingnumber": "\u0004 Not Applicable", 
                            "dynamiccstiscleared": false, 
                            "amount": "600.00", 
                            "actualqty": " 60.00 nos", 
                            "billedqty": " 60.00 nos"
                        }
                    ], 
                    "accountingallocations": [
                        {
                            "oldauditentryids": [
                                {
                                    "metadata": true, 
                                    "type": "Number"
                                }, 
                                "-1"
                            ], 
                            "ledgername": "Sales @ 5 GST", 
                            "gstclass": "\u0004 Not Applicable", 
                            "isdeemedpositive": false, 
                            "ledgerfromitem": false, 
                            "removezeroentries": false, 
                            "ispartyledger": false, 
                            "gstoverridden": false, 
                            "isgstassessablevalueoverridden": false, 
                            "strdisgstapplicable": false, 
                            "strdgstispartyledger": false, 
                            "strdgstisdutyledger": false, 
                            "contentnegispos": false, 
                            "islastdeemedpositive": false, 
                            "iscapvattaxaltered": false, 
                            "iscapvatnotclaimed": false, 
                            "amount": "600.00"
                        }
                    ]
                }, 
                {
                    "stockitemname": "Pencile", 
                    "isdeemedpositive": false, 
                    "isgstassessablevalueoverridden": false, 
                    "strdisgstapplicable": false, 
                    "contentnegispos": false, 
                    "islastdeemedpositive": false, 
                    "isautonegate": false, 
                    "iscustomsclearance": false, 
                    "istrackcomponent": false, 
                    "istrackproduction": false, 
                    "isprimaryitem": false, 
                    "isscrap": false, 
                    "rate": "5.00/nos", 
                    "amount": "200.00", 
                    "actualqty": " 40.00 nos", 
                    "billedqty": " 40.00 nos", 
                    "batchallocations": [
                        {
                            "godownname": "Main Location", 
                            "batchname": "Primary Batch", 
                            "indentno": "\u0004 Not Applicable", 
                            "orderno": "\u0004 Not Applicable", 
                            "trackingnumber": "\u0004 Not Applicable", 
                            "dynamiccstiscleared": false, 
                            "amount": "200.00", 
                            "actualqty": " 40.00 nos", 
                            "billedqty": " 40.00 nos"
                        }
                    ], 
                    "accountingallocations": [
                        {
                            "oldauditentryids": [
                                {
                                    "metadata": true, 
                                    "type": "Number"
                                }, 
                                "-1"
                            ], 
                            "ledgername": "Sales @ 5 GST", 
                            "gstclass": "\u0004 Not Applicable", 
                            "isdeemedpositive": false, 
                            "ledgerfromitem": false, 
                            "removezeroentries": false, 
                            "ispartyledger": false, 
                            "gstoverridden": false, 
                            "isgstassessablevalueoverridden": false, 
                            "strdisgstapplicable": false, 
                            "strdgstispartyledger": false, 
                            "strdgstisdutyledger": false, 
                            "contentnegispos": false, 
                            "islastdeemedpositive": false, 
                            "iscapvattaxaltered": false, 
                            "iscapvatnotclaimed": false, 
                            "amount": "200.00"
                        }
                    ]
                }
            ], 
            "ledgerentries": [
                {
                    "oldauditentryids": [
                        {
                            "metadata": true, 
                            "type": "Number"
                        }, 
                        "-1"
                    ], 
                    "ledgername": "Kumar2", 
                    "gstclass": "\u0004 Not Applicable", 
                    "isdeemedpositive": true, 
                    "ledgerfromitem": false, 
                    "removezeroentries": false, 
                    "ispartyledger": true, 
                    "gstoverridden": false, 
                    "isgstassessablevalueoverridden": false, 
                    "strdisgstapplicable": false, 
                    "strdgstispartyledger": false, 
                    "strdgstisdutyledger": false, 
                    "contentnegispos": false, 
                    "islastdeemedpositive": true, 
                    "iscapvattaxaltered": false, 
                    "iscapvatnotclaimed": false, 
                    "amount": "-800.00", 
                    "billallocations": [
                        {
                            "name": "1", 
                            "billtype": "New Ref", 
                            "tdsdeducteeisspecialrate": false, 
                            "amount": "-800.00"
                        }
                    ]
                }
            ]
        }
    ]
}